### ISSUE TITLE
AHRC digital infrastructure policy fellows

### ISSUE THREAD

**Issue by kmcdono2** [fedenanni/HDS-DiscussionGroup#19]
Draft text for email to Melodee and Anna-Maria below. Requests for changes etc. welcome! @fedenanni @malvikasharan and others

> Dear Melodee and Ana Maria,
> 
> I am writing on behalf of the organizing team of the Turing Humanities & Data Science Discussion Group to invite you both to discuss your new roles as the AHRC Policy and Engagement Fellows. 
> 
> The Discussion Group sits under the umbrella of the Humanities & Data Science SIG at the Turing. We’ve been taking a bit of a break from events, but this spring we are re-starting with some fresh ideas. Our two main goals are to build community among ECRs in DH around the UK and to connect the Turing DH community with existing centers, labs, groups in the UK.
> 
> To this end, we would love to learn about the ideas and challenges you’ve been developing through these positions with the AHRC. If you are interested, we suggest organizing a 1 hour event on the last Wednesday of April (27th). We are flexible on the time of day. In the past we’ve done lunchtime and mid afternoon. If the date is inconvenient, we are very happy to move this event to another month.
> 
> For the event itself, we don’t expect a formal presentation. It would be wonderful if you could share some materials in advance for participants to read, we welcome links to, for example:
> 
> - a website with a description of what your roles as fellows entails
> - any materials that you might have produced during your work thus far and would like to share and discuss
> - any other materials online that relate to the brief of your fellowship (e.g. a white paper from AHRC/UKRI or similar)
> 
> Lastly, if you’re willing to speak briefly (5 min each?) at the outset of the discussion, this could help get things rolling. We would be happy to chat with you in advance to come up with some mutually interesting discussion questions!
> 
> We look forward to hearing from you both and hope you’ll be able to accept. 
> 
> Best,
> Katie

**Comment by fedenanni** [comment]
Maybe we can skip this part `We’ve been taking a bit of a break from events, but this spring we are re-starting with some fresh ideas` or add that the group has been running since 2020 and that we have have taken a bit of a break in thee second part of 2021

**Comment by fedenanni** [comment]
The rest looks great - thanks a lot!

**Comment by kmcdono2** [comment]
OK here's the final text:

> Dear Melodee and Ana Maria,
> 
> I am writing on behalf of the organizing team of the [Turing Humanities & Data Science Discussion Group](https://github.com/alan-turing-institute/HDS-DiscussionGroup) to invite you both to discuss your new roles as the AHRC Policy and Engagement Fellows. 
> 
> The Discussion Group sits under the umbrella of the [Humanities & Data Science SIG](https://www.turing.ac.uk/research/interest-groups/humanities-and-data-science) at the Turing. The group has been running since 2020 and we are restarting after a break in the second half of 2021. Our two main goals are to build community among ECRs in DH around the UK and to connect the Turing DH community with existing centers, labs, groups in the UK.
> 
> To this end, we would love to learn about the ideas and challenges you’ve been developing/considering through these positions with the AHRC. If you are interested, we suggest organizing a 1 hour event on the last Wednesday of April (27th). We are flexible on the time of day. In the past we’ve done lunchtime and mid afternoon. If the date is inconvenient, we are very happy to move this event to another month.
> 
> For the event itself, we don’t expect a formal presentation. It would be wonderful if you could share some materials in advance for participants to review. For example, we welcome links to:
> 
> - a website with a description of what your roles as fellows entails
> - materials that you might have produced during your work thus far and would like to share and discuss
> - other materials online that relate to the brief of your fellowship (e.g. a white paper from AHRC/UKRI or similar)
> 
> Lastly, if you’re willing to speak briefly (5 min each?) at the outset of the discussion, this could help get things rolling. We would be happy to chat with you in advance to come up with some mutually interesting discussion questions!
> 
> We look forward to hearing from you both and hope you’ll be able to accept.

**Comment by amsichani** [comment]
Hi there! Glad to be onboard! Looking forward to meeting you in person soon!
