### ISSUE TITLE
Add new members to the README

### ISSUE THREAD

**Issue by malvikasharan** [fedenanni/HDS-DiscussionGroup#21]
We have new members joining the organising commmittee, we should update that information.

## TODO

Ask following people to add their details in this thread
- [ ] Valeria Vitale
- [x] Kalle Westerling
- [x] Anne Lee Steele
- [ ] Anna Maria S. (?)

**Comment by kallewesterling** [comment]
@kallewesterling here!

**Comment by aleesteele** [comment]
@aleesteele here!
